name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Install diesel_cli
      run: cargo install diesel_cli --no-default-features --features sqlite
    - name: Setup database
      run: diesel setup
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
